default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5434 } %>
  username: <%= ENV.fetch("DB_USERNAME") { "pulse_watch" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "pulse_watch" } %>

development:
  <<: *default
  database: pulse_watch_development

test:
  <<: *default
  database: pulse_watch_test

production:
  primary: &primary_production
    <<: *default
    database: pulse_watch_production
    username: pulse_watch
    password: <%= ENV["PULSE_WATCH_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: pulse_watch_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: pulse_watch_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: pulse_watch_production_cable
    migrations_paths: db/cable_migrate
